<script setup>
import { watch } from 'vue';
import { usePatientStore } from '../../../../store/injury/PatientStore';
import CheckBoxMultiple from '../../../custom/checkBoxMultiple.vue';
import { autoGeneratedObjSubjDiag } from '../../../../composables/autoGeneratedObjSubjDiag';

const PatientStore = usePatientStore();

// Create refs for all necessary fields
const bitingOptions = ['ALIVE', 'DIED', 'UNKNOWN'];
const woundDescriptionOptions = ['HEALED', 'DRY', 'OTHERS'];
const positive_negative_option = ['+', '-'];
const findingOption = ['ESSENTIALLY NORMAL PE FINDING', 'WITH FINDINGS'];
const immunizationOption = ['PRIMARY REGIMEN', 'BOOSTER'];
const hovering = false;

function handleClick() {
    PatientStore.details.ABTC.immunization_schedule = '';
}
// Import the composable function
const { generateText } = autoGeneratedObjSubjDiag();

watch(
    () => [PatientStore.details.generalData, PatientStore.details.ABTC, PatientStore.details.preAdmissionData, PatientStore.details.forTransportVehicularAccident, PatientStore.details.ExternalCauseOfInjury, PatientStore.details.natureOfInjury],
    () => {
        generateText();
    },
    { deep: true }
);
</script>
<template>
    <h5 style="text-align: center; font-weight: bolder; color: #333">FOLLOW-UP FORM</h5>

    <div style="width: 100%" class="flex justify-content-evenly">
        <Fieldset style="width: 48%" pt:content:class="flex justify-center" :pt="{ legend: { style: { border: 'none', backgroundColor: 'transparent' } }, toggler: { style: { padding: '0rem' } } }">
            <template #legend>
                <span style="color: #000080" class="font-bold white-space-nowrap">Subjective</span>
            </template>

            <div>
                <label for="complaints" class="text-black text-xs" style="color: #000080"><i>complaints </i></label>
                <div>
                    <Textarea style="width: 100%" v-model="PatientStore.details.followUp.complaints" rows="1" class="justify-content-center font-bold" autoResize />
                </div>
            </div>

            <div>
                <label for="Adverse" class="text-black text-xs" style="color: #000080"><i>Adverse reaction from previous vaccination </i></label>
                <div>
                    <Textarea style="width: 100%" v-model="PatientStore.details.followUp.adverse_reaction" rows="1" class="justify-content-center font-bold" autoResize />
                </div>
            </div>

            <div style="width: 100%" v-if="PatientStore.type_prophylaxis === 'POST-EXPOSURE'">
                <label for="Biting" class="text-black text-xs" style="color: #000080"><i>Biting </i></label>
                <SelectButton
                    v-model="PatientStore.details.followUp.biting"
                    :options="bitingOptions"
                    aria-labelledby="basic"
                    :pt="{
                        root: {
                            style: { width: '100%' }
                        },
                        button: {
                            style: {
                                width: '33%'
                            }
                        }
                    }"
                />
            </div>

            <div>
                <label for="others" class="text-black text-xs" style="color: #000080"><i>Others</i></label>
                <div>
                    <Textarea style="width: 100%" v-model="PatientStore.details.followUp.others" rows="1" class="justify-content-center font-bold" autoResize />
                </div>
            </div>
        </Fieldset>

        <Fieldset style="width: 48%" pt:content:class="flex justify-center" :pt="{ legend: { style: { border: 'none', backgroundColor: 'transparent' } }, toggler: { style: { padding: '1rem' } } }">
            <template #legend>
                <span style="color: #000080" class="font-bold white-space-nowrap">Objective</span>
            </template>
            <div v-if="PatientStore.type_prophylaxis === 'POST-EXPOSURE'">
                <div style="width: 100%">
                    <label for="woundDesc" class="text-black text-xs" style="color: #000080"><i>Wound Description</i></label>
                    <Dropdown style="width: 98%" id="woundDescription" class="font-bold" v-model="PatientStore.details.followUp.wound_description" :options="woundDescriptionOptions" />
                    <div v-if="PatientStore.details.followUp.wound_description === 'OTHERS'">
                        <label for="woundOthDescription" class="text-black text-xs" style="color: #000080"><i>Others</i></label>
                        <Textarea style="width: 98%" id="woundOthDescription" v-model="PatientStore.details.followUp.wound_descriptionOthers" rows="1" class="mt-2 justify-content-center font-bold" autoResize />
                    </div>
                </div>

                <div style="width: 100%">
                    <label for="Erythema" class="text-black text-xs" style="color: #000080"><i>Erythema </i></label>
                    <SelectButton
                        v-model="PatientStore.details.followUp.erythema"
                        :options="positive_negative_option"
                        aria-labelledby="basic"
                        :pt="{
                            root: {
                                style: { width: '100%' }
                            },
                            button: {
                                style: {
                                    width: '49%'
                                }
                            }
                        }"
                    />
                </div>

                <div style="width: 100%">
                    <label for="Discharge" class="text-black text-xs" style="color: #000080"><i>Discharge </i></label>
                    <SelectButton
                        v-model="PatientStore.details.followUp.discharge"
                        :options="positive_negative_option"
                        aria-labelledby="basic"
                        :pt="{
                            root: {
                                style: { width: '100%' }
                            },
                            button: {
                                style: {
                                    width: '49%'
                                }
                            }
                        }"
                    />
                    <div v-if="PatientStore.details.followUp.discharge === '+'">
                        <label for="Discharge" class="text-black text-xs" style="color: #000080"><i>Discharge Description </i></label>
                        <Textarea v-model="PatientStore.details.followUp.discharge_sp" style="width: 100%; font-weight: bold" />
                    </div>
                </div>
                <div style="width: 100%">
                    <label for="Tenderness" class="text-black text-xs" style="color: #000080"><i>Tenderness </i></label>
                    <SelectButton
                        v-model="PatientStore.details.followUp.tenderness"
                        :options="positive_negative_option"
                        aria-labelledby="basic"
                        :pt="{
                            root: {
                                style: { width: '100%' }
                            },
                            button: {
                                style: {
                                    width: '49%'
                                }
                            }
                        }"
                    />
                </div>
                <div style="width: 100%">
                    <label for="Hematoma" class="text-black text-xs" style="color: #000080"><i>Hematoma </i></label>
                    <SelectButton
                        v-model="PatientStore.details.followUp.hematoma"
                        :options="positive_negative_option"
                        aria-labelledby="basic"
                        :pt="{
                            root: {
                                style: { width: '100%' }
                            },
                            button: {
                                style: {
                                    width: '49%'
                                }
                            }
                        }"
                    />
                </div>
            </div>
            <div v-else>
                <div style="width: 100%">
                    <label for="Finding" class="text-black text-xs" style="color: #000080"><i>Finding </i></label>
                    <SelectButton
                        v-model="PatientStore.details.followUp.finding"
                        :options="findingOption"
                        aria-labelledby="basic"
                        :pt="{
                            root: {
                                style: { width: '100%' }
                            },
                            button: {
                                style: {
                                    width: '49%'
                                }
                            }
                        }"
                    />
                    <label for="Tenderness" v-if="PatientStore.details.followUp.finding === 'WITH FINDINGS'" class="text-black text-xs" style="color: #000080; width: 100%"><i>Finding </i></label>
                    <Textarea v-if="PatientStore.details.followUp.finding === 'WITH FINDINGS'" v-model="PatientStore.details.followUp.finding_sp" style="width: 100%; font-weight: bold" />
                </div>
            </div>
        </Fieldset>
    </div>

    <div class="flex justify-content-center">
        <Fieldset style="width: 98%" pt:content:class="flex" :pt="{ legend: { style: { border: 'none', backgroundColor: 'transparent' } }, toggler: { style: { padding: '1rem' } } }">
            <template #legend>
                <span style="color: #000080" class="flex justify-content-center font-bold white-space-nowrap">Vaccine to be Given ( {{ PatientStore.type_prophylaxis }} ) </span>
                <span style="color: blue; font-size: x-small; cursor: pointer; transition: color 0.3s" @click="handleClick" @mouseover="hovering = true" @mouseleave="hovering = false" :style="{ color: hovering ? 'darkblue' : 'blue' }">
                    {{ PatientStore.details.ABTC.immunization_schedule }}
                </span>
            </template>
            <div v-if="PatientStore.details.ABTC.immunization_schedule === ''">
                <div style="width: 100%">
                    <label for="Finding" class="text-black text-xs" style="color: #000080"><i>Immunization Schedule </i></label>
                    <SelectButton
                        v-model="PatientStore.details.ABTC.immunization_schedule"
                        :options="immunizationOption"
                        aria-labelledby="basic"
                        :pt="{
                            root: {
                                style: { width: '100%' }
                            },
                            button: {
                                style: {
                                    width: '49%'
                                }
                            }
                        }"
                    />
                    <label for="Tenderness" v-if="PatientStore.details.followUp.finding === 'WITH FINDINGS'" class="text-black text-xs" style="color: #000080; width: 100%"><i>Finding </i></label>
                    <Textarea v-if="PatientStore.details.followUp.finding === 'WITH FINDINGS'" v-model="PatientStore.details.followUp.finding_sp" style="width: 100%; font-weight: bold" />
                </div>
            </div>
            <div v-else>
                <!-- {{ PatientStore.progressionDay }}
                {{ PatientStore.details.ABTC }}
                {{ PatientStore.type_prophylaxis }} -->
                <div class="grid grid-cols-4 gap-4 flex justify-content-evenly">
                    <CheckBoxMultiple class="justify-content-center" style="width: 13%" v-model="PatientStore.details.ABTC.pvrv" label="PVRV" />
                    <CheckBoxMultiple class="justify-content-center" style="width: 13%" v-model="PatientStore.details.ABTC.pcec" label="PCEC" />
                    <CheckBoxMultiple v-if="PatientStore.type_prophylaxis === 'POST-EXPOSURE'" class="justify-content-center" style="width: 10%" v-model="PatientStore.details.ABTC.hrig" label="HRIG" />
                    <CheckBoxMultiple v-if="PatientStore.type_prophylaxis === 'POST-EXPOSURE'" class="justify-content-center" style="width: 10%" v-model="PatientStore.details.ABTC.erig" label="ERIG" />
                    <CheckBoxMultiple v-if="PatientStore.type_prophylaxis === 'POST-EXPOSURE'" class="justify-content-center" style="width: 10%" v-model="PatientStore.details.ABTC.ats" label="ATS" />
                    <CheckBoxMultiple class="justify-content-center" style="width: 8%" v-model="PatientStore.details.ABTC.tt" label="TT" />
                    <CheckBoxMultiple class="justify-content-center" style="width: 8%" v-model="PatientStore.details.ABTC.vaccine_none" label="NONE" />
                </div>
                <div class="grid grid-cols-4 gap-4 justify-content-evenly mt-3">
                    <div style="width: 13%">
                        <Transition name="slide-fade" mode="out-in">
                            <div v-if="PatientStore.details.ABTC.pvrv === 'Y'" style="width: 100%" class="flex justify-content-evenly mb-2">
                                <CheckBoxMultiple class="flex justify-content-center" style="width: 35%" v-model="PatientStore.details.ABTC.pvrv_site_2" label="2-sites" />
                                <CheckBoxMultiple class="flex justify-content-center" style="width: 35%" v-model="PatientStore.details.ABTC.pvrv_site_4" label="4-sites" />
                            </div>
                        </Transition>
                    </div>
                    <div style="width: 13%">
                        <Transition name="slide-fade" mode="out-in">
                            <div v-if="PatientStore.details.ABTC.pcec === 'Y'" style="width: 100%" class="flex justify-content-evenly mb-2">
                                <CheckBoxMultiple class="flex justify-content-center" style="width: 35%" v-model="PatientStore.details.ABTC.pcec_site_2" label="2-sites" />
                                <CheckBoxMultiple class="flex justify-content-center" style="width: 35%" v-model="PatientStore.details.ABTC.pcec_site_4" label="4-sites" />
                            </div>
                        </Transition>
                    </div>
                    <div style="width: 10%">
                        <Transition name="slide-fade" mode="out-in">
                            <div v-if="PatientStore.details.ABTC.hrig === 'Y'" style="width: 100%" class="flex justify-content-evenly">
                                <div class="field">
                                    <span class="p-float-label">
                                        <InputNumber type="number" suffix=" mL" :min="0" :max="25" id="hrig" v-model="PatientStore.details.ABTC.hrig_num" />
                                        <label for="hrig">Amount to be Given</label>
                                    </span>
                                </div>
                            </div>
                        </Transition>
                    </div>
                    <div style="width: 10%">
                        <Transition name="slide-fade" mode="out-in">
                            <div v-if="PatientStore.details.ABTC.erig === 'Y'" style="width: 100%" class="flex justify-content-evenly">
                                <div class="field">
                                    <span class="p-float-label">
                                        <InputNumber type="number" suffix=" mL" :min="0" :max="25" id="erig" v-model="PatientStore.details.ABTC.erig_num" />
                                        <label for="erig">Amount to be Given</label>
                                    </span>
                                </div>
                            </div>
                        </Transition>
                    </div>
                    <div style="width: 10%">
                        <Transition name="slide-fade" mode="out-in">
                            <div v-if="PatientStore.details.ABTC.ats === 'Y'" style="width: 100%" class="flex justify-content-evenly">
                                <div class="field" style="width: 100%">
                                    <span class="p-float-label">
                                        <Dropdown
                                            style="width: 80%"
                                            v-model="PatientStore.details.ABTC.ats_num"
                                            :options="[
                                                { label: '1500 ui', value: '1500' },
                                                { label: '3000 ui', value: '3000' },
                                                { label: '4500 ui', value: '4500' },
                                                { label: '6000 ui', value: '6000' }
                                            ]"
                                            optionLabel="label"
                                            optionValue="value"
                                        />
                                        <label for="ats">Amount to be Given</label>
                                    </span>
                                </div>
                            </div>
                        </Transition>
                    </div>
                    <div style="width: 8%"></div>
                    <div style="width: 8%"></div>
                    <!-- <div
                    v-if="
                        (PatientStore.details.ABTC.pvrv !== 'Y' &&
                            PatientStore.details.ABTC.pcec !== 'Y' &&
                            PatientStore.details.ABTC.hrig !== 'Y' &&
                            PatientStore.details.ABTC.erig !== 'Y' &&
                            PatientStore.details.ABTC.tt !== 'Y' &&
                            PatientStore.details.ABTC.ats !== 'Y' &&
                            PatientStore.details.ABTC.vaccine_none !== 'Y') ||
                        (PatientStore.details.ABTC.pvrv_site_2 !== 'Y' && PatientStore.details.ABTC.pvrv_site_4 !== 'Y' && PatientStore.details.ABTC.pvrv === 'Y') ||
                        (PatientStore.details.ABTC.pcec_site_2 !== 'Y' && PatientStore.details.ABTC.pcec_site_4 !== 'Y' && PatientStore.details.ABTC.pcec === 'Y') ||
                        (PatientStore.details.ABTC.hrig === 'Y' && PatientStore.details.ABTC.hrig_num === '') ||
                        (PatientStore.details.ABTC.erig === 'Y' && PatientStore.details.ABTC.erig_num === '') ||
                        (PatientStore.details.ABTC.ats === 'Y' && PatientStore.details.ABTC.ats_num === '')
                    "
                    class="bg-red-200 p-2 bottom-0 left-0 text-center text-gray-700 font-semibold italic"
                    style="border-radius: 0 0 1rem 1rem; width: 100%; font-size: 1rem; margin: 0 !important"
                >
                    Value is Required
                </div> -->
                </div>
            </div>
        </Fieldset>
    </div>

    <div class="flex justify-content-center mt-3">
        <Fieldset
            style="width: 96%"
            :toggleable="true"
            :collapsed="true"
            :pt="{
                root: { style: { backgroundColor: 'transparent', border: 'none', padding: 'none' } },
                legend: { style: { border: 'none', backgroundColor: 'transparent', textAlign: 'center' } },
                toggler: { style: { padding: '1rem' } }
            }"
        >
            <template #legend>
                <span style="color: #000080" class="font-bold white-space-nowrap">Customize Diagnosis</span>
            </template>
            <Textarea
                :pt="{
                    root: {
                        style: {
                            width: '100%',
                            overflow: 'hidden',
                            border: '2px dashed #ccc',
                            borderRadius: '4px',
                            padding: '5px',
                            boxSizing: 'border-box',
                            resize: 'none',
                            backgroundColor: '#ececec',
                            color: '#666',
                            fontWeight: 'bold',
                            fontSize: '13px'
                        }
                    }
                }"
                style="width: 100%"
                v-model="PatientStore.header.doctor_diagnosis"
                class="mt-1 justify-content-center"
                autoResize
            />
        </Fieldset>
    </div>
</template>

<style scoped></style>
