name: "🐞 Bug Report"
description: "Report a bug or issue in the application."
title: "🐞 [Bug] "
labels: ["🐞 type/bug"]
assignees:
  - nad
body:
  - type: textarea
    id: summary
    attributes:
      label: "🔍 Summary"
      description: "A brief overview of the bug."
      placeholder: "Describe the bug in one or two sentences."
    validations:
      required: true

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: "🔄 Steps to Reproduce"
      description: "List the steps to reproduce the bug."
      placeholder: |
        1. Step one
        2. Step two
        3. Step three
    validations:
      required: true

  - type: textarea
    id: expected_behavior
    attributes:
      label: "✅ Expected Behavior"
      description: "What did you expect to happen?"
      placeholder: "Describe what you expected to occur."
    validations:
      required: true

  - type: textarea
    id: actual_behavior
    attributes:
      label: "❌ Actual Behavior"
      description: "What actually happened?"
      placeholder: "Describe what happened instead."
    validations:
      required: true

  - type: textarea
    id: additional_details
    attributes:
      label: "📜 Additional Details"
      description: "Any other relevant information, screenshots, or logs?"
      placeholder: "Include any other context that might help."
