<script setup>
import { usePatientStore } from '../../../../../store/injury/patientStore';
import { ref, onMounted, watch, Text } from 'vue';
import moment from 'moment';
import InputText from 'primevue/inputtext';
import CheckBoxMultiple from '../../../../custom/checkBoxMultiple.vue';
// import { autoGeneratedObjSubjDiag } from '../../../../../composables/autoGeneratedObjSubjDiag';
import VaccineForm from '../../opd/vaccineForm.vue';

// Import the composable function
// const { generateText } = autoGeneratedObjSubjDiag();

const hovering = ref(false);
// Reactive references for date inputs
const yearOnly = ref(null);
const monthYear = ref(null);
const completeDate = ref(null);
const lastTetanusDoseYear = ref(null);
const lastTetanusDoseMonthYear = ref(null);
const boosterRegimenOption = ['1-DAY REGIMEN', '2-DAY REGIMEN'];
const immunizationOption = ['PRIMARY REGIMEN', 'BOOSTER'];
const lastTetanusDoseCompleteDate = ref(null);
const positive_negative_option = ['+', '-'];
const vaccineNoneOption = ['NO ARV NEEDED', 'STILL COVERED'];
const patientStore = usePatientStore();
const coveredDate = ref(null);
const animal = ref();
const cause = ref();
// const typesOfProphylaxis = ['PRE-EXPOSURE', 'POST-EXPOSURE'];

const handleCoverdDateSelect = () => {
    const formattedDate = moment(coveredDate.value).format('MM/DD/YYYY');
    patientStore.details.ABTC.coveredDate = formattedDate;
};

// Function to handle ARV date selection
const handlePreviousAntiTetanous = (type) => {
    const date = type === 'year' ? yearOnly.value : type === 'month' ? monthYear.value : completeDate.value;
    const formattedDate = moment(date).format(type === 'year' ? '00/00/YYYY' : type === 'month' ? 'MM/00/YYYY' : 'MM/DD/YYYY');
    patientStore.details.ExternalCauseOfInjury.arvDate = formattedDate;
};

// Function to handle last tetanus dose selection
const handleLastTetanusDoseSelect = (type) => {
    const date = type === 'year' ? lastTetanusDoseYear.value : type === 'month' ? lastTetanusDoseMonthYear.value : lastTetanusDoseCompleteDate.value;
    const formattedDate = moment(date).format(type === 'year' ? '00/00/YYYY' : type === 'month' ? 'MM/00/YYYY' : 'MM/DD/YYYY');
    patientStore.details.ExternalCauseOfInjury.lastTetanusDose = formattedDate;
};

// Options for various dropdowns
const bleedingOptions = [
    { label: 'None', value: 'NONE' },
    { label: 'Spontaneous', value: 'SPONTANEOUS' },
    { label: 'Induced', value: 'INDUCED' }
];

const bitingAnimalOptions = [
    { label: 'Vaccinated', value: 'VACCINATED' },
    { label: 'Unvaccinated', value: 'UNVACCINATED' }
];

const observationOptions = [
    { label: 'Yes', value: 'YES' },
    { label: 'No', value: 'NO' }
];

const previousARVOption = [
    { label: 'Yes', value: 'YES' },
    { label: 'No', value: 'NO' },
    { label: 'Completed Primary DPT Doses', value: 'COMPLETED PRIMARY DPT DOSES' }
];

const animalOption = [
    { label: 'Dog', value: 'DOG' },
    { label: 'Cat', value: 'CAT' },
    { label: 'Rat', value: 'RAT' },
    { label: 'Pig', value: 'PIG' },
    { label: 'Monkey', value: 'MONKEY' },
    { label: 'Human', value: 'HUMAN' },
    { label: 'Others', value: 'OTHERS' }
];

const causeOption = [
    { label: 'Bite', value: 'BITE' },
    { label: 'Scratch', value: 'SCRATCH' },
    { label: 'Licking of Open Wound', value: 'LICKING' },
    { label: 'Ingestion of Meat', value: 'INGEST' },
    { label: 'Saliva', value: 'SALIVA' },
    { label: 'Exposure', value: 'EXPOSURE' },
    { label: 'Others', value: 'OTHERS' }
];

const washingOptions = [
    { label: 'Yes', value: 'YES' },
    { label: 'No', value: 'NO' }
];

const appliedOptions = [
    { label: 'Yes', value: 'Y' },
    { label: 'No', value: 'N' }
];

const biteDegreeOptions = [
    { label: 'Category level I', value: 'I' },
    { label: 'Category level II', value: 'II' },
    { label: 'Category level III', value: 'III' }
];

function handleClick() {
    patientStore.details.ABTC.immunization_schedule = '';
    patientStore.details.ABTC.booster_regimen = '';
}

function addExternalCause() {
    patientStore.details.ExternalCauseOfInjury.animal.push('');
    patientStore.details.ExternalCauseOfInjury.cause.push('');
    patientStore.details.ExternalCauseOfInjury.animal_sp.push('');
    patientStore.details.ExternalCauseOfInjury.cause_sp.push('');
}

function removeExternalCause(index) {
    patientStore.details.ExternalCauseOfInjury.animal.splice(index, 1);
    patientStore.details.ExternalCauseOfInjury.cause.splice(index, 1);
    patientStore.details.ExternalCauseOfInjury.animal_sp.splice(index, 1);
    patientStore.details.ExternalCauseOfInjury.cause_sp.splice(index, 1);
}
// Lifecycle hook to initialize date values
onMounted(async () => {
    if (patientStore.details.ExternalCauseOfInjury.arvDate) {
        const arvDateString = patientStore.details.ExternalCauseOfInjury.arvDate;

        const parts = arvDateString.split('/');

        if (parts[0] == '00' && parts[1] == '00') {
            const yearOnlys = parts[2];
            yearOnly.value = yearOnlys;
        } else if (parts[0] == '00') {
            const month = parts[1];
            const year = parts[2];
            const monthYears = `${month}/${year}`;
            monthYear.value = monthYears;
        } else if (parts.length === 3 && parts[2].length === 4) {
            const month = parseInt(parts[0], 10) - 1;
            const day = parseInt(parts[1], 10);
            const year = parts[2];
            const completeDates = new Date(year, month, day);

            if (!isNaN(completeDates.getTime())) {
                completeDate.value = completeDates;
            } else {
                console.error('Invalid date for completeDate');
            }
        } else {
            console.error('Invalid date format');
        }
    }

    if (patientStore.details.ExternalCauseOfInjury.lastTetanusDose) {
        const arvDateString = patientStore.details.ExternalCauseOfInjury.lastTetanusDose;
        console.log('Raw arvDate:', arvDateString.split('/'));

        const parts = arvDateString.split('/');

        if (parts[0] == '00' && parts[1] == '00') {
            const yearOnlys = parts[2];
            lastTetanusDoseYear.value = yearOnlys;
        } else if (parts[0] == '00') {
            const month = parts[1];
            const year = parts[2];
            const monthYears = `${month}/${year}`;
            lastTetanusDoseMonthYear.value = monthYears;
        } else if (parts.length === 3 && parts[2].length === 4) {
            const month = parseInt(parts[0], 10) - 1;
            const day = parseInt(parts[1], 10);
            const year = parts[2];
            const completeDates = new Date(year, month, day);

            if (!isNaN(completeDates.getTime())) {
                lastTetanusDoseCompleteDate.value = completeDates;
            } else {
                console.error('Invalid date for completeDate');
            }
        } else {
            console.error('Invalid date format');
        }
    }
    // generateText();
});

//watch changes on generatedText
// watch(
//     () => [
//         patientStore.details.generalData,
//         patientStore.details.ABTC,
//         patientStore.details.preAdmissionData,
//         patientStore.details.forTransportVehicularAccident,
//         patientStore.details.ExternalCauseOfInjury,
//         patientStore.details.natureOfInjury,
//         patientStore.details.followUp
//     ],
//     () => {
//         generateText();
//     },
//     { deep: true }
// );

// watch(
//     () => patientStore.details.multipleFields,
//     () => {
//         generateText();
//     },
//     { deep: true }
// );)

//watch animal and cause then save it as animal + cause =  patientStore.details.ExternalCauseOfInjury.ext_bite_sp
// watch(
//     () => [patientStore.details.ExternalCauseOfInjury.animal, patientStore.details.ExternalCauseOfInjury.cause, patientStore.details.ExternalCauseOfInjury.animal_sp, patientStore.details.ExternalCauseOfInjury.cause_sp],
//     () => {
//         if (patientStore.details.ExternalCauseOfInjury.animal && patientStore.details.ExternalCauseOfInjury.cause) {
//             if (patientStore.details.ExternalCauseOfInjury.cause === 'OTHERS' && patientStore.details.ExternalCauseOfInjury.animal === 'OTHERS') {
//                 // alert('hit');
//                 patientStore.details.ExternalCauseOfInjury.ext_bite_sp = patientStore.details.ExternalCauseOfInjury.animal_sp + ' ' + patientStore.details.ExternalCauseOfInjury.cause_sp;
//             } else if (patientStore.details.ExternalCauseOfInjury.cause === 'OTHERS') {
//                 // alert('hits');
//                 patientStore.details.ExternalCauseOfInjury.ext_bite_sp = patientStore.details.ExternalCauseOfInjury.animal + ' ' + patientStore.details.ExternalCauseOfInjury.cause_sp;
//             } else if (patientStore.details.ExternalCauseOfInjury.animal === 'OTHERS') {
//                 // alert('hitss');
//                 patientStore.details.ExternalCauseOfInjury.ext_bite_sp = patientStore.details.ExternalCauseOfInjury.animal_sp + ' ' + patientStore.details.ExternalCauseOfInjury.cause;
//             } else {
//                 // alert('hitsss');
//                 patientStore.details.ExternalCauseOfInjury.ext_bite_sp = patientStore.details.ExternalCauseOfInjury.animal + ' ' + patientStore.details.ExternalCauseOfInjury.cause;
//             }
//         }
//     }
// );
watch(
    () => [patientStore.details.ExternalCauseOfInjury.animal, patientStore.details.ExternalCauseOfInjury.cause, patientStore.details.ExternalCauseOfInjury.animal_sp, patientStore.details.ExternalCauseOfInjury.cause_sp],
    () => {
        const animals = patientStore.details.ExternalCauseOfInjury.animal;
        const causes = patientStore.details.ExternalCauseOfInjury.cause;
        const animalSP = patientStore.details.ExternalCauseOfInjury.animal_sp;
        const causeSP = patientStore.details.ExternalCauseOfInjury.cause_sp;

        const result = animals.map((animal, i) => {
            const cause = causes[i];
            const aSP = animalSP[i] || '';
            const cSP = causeSP[i] || '';

            if (animal === 'OTHERS' && cause === 'OTHERS') {
                return aSP + ' ' + cSP;
            } else if (animal === 'OTHERS') {
                return aSP + ' ' + cause;
            } else if (cause === 'OTHERS') {
                return animal + ' ' + cSP;
            } else {
                return animal + ' ' + cause;
            }
        });

        // Join with comma or space depending on your need
        patientStore.details.ExternalCauseOfInjury.ext_bite_sp = result.join(', ');
    },
    { deep: true }
);
watch(
    () => patientStore.details.ABTC.skintest,
    (newValue) => {
        if (newValue === '+') {
            patientStore.details.ABTC.hrig = 'Y';
        } else {
            patientStore.details.ABTC.hrig = 'N';
        }
    }
);
// Watch for pvrv values
// watch(
//     () => [patientStore.details.ABTC.pvrv_site_1_id, patientStore.details.ABTC.pvrv_site_1_im, patientStore.details.ABTC.pvrv_site_2, patientStore.details.ABTC.pvrv_site_4],
//     (newValues) => {
//         if (newValues.some((value) => value === 'Y')) {
//             patientStore.details.ABTC.pvrv_site_1_id = newValues[0] === 'Y' ? 'Y' : 'N';
//             patientStore.details.ABTC.pvrv_site_1_im = newValues[1] === 'Y' ? 'Y' : 'N';
//             patientStore.details.ABTC.pvrv_site_2 = newValues[2] === 'Y' ? 'Y' : 'N';
//             patientStore.details.ABTC.pvrv_site_4 = newValues[3] === 'Y' ? 'Y' : 'N';
//         }
//     }
// );

// // Watch for pcec values
// watch(
//     () => [patientStore.details.ABTC.pcec_site_1_id, patientStore.details.ABTC.pcec_site_1_im, patientStore.details.ABTC.pcec_site_2, patientStore.details.ABTC.pcec_site_4],
//     (newValues) => {
//         if (newValues.some((value) => value === 'Y')) {
//             patientStore.details.ABTC.pcec_site_1_id = newValues[0] === 'Y' ? 'Y' : 'N';
//             patientStore.details.ABTC.pcec_site_1_im = newValues[1] === 'Y' ? 'Y' : 'N';
//             patientStore.details.ABTC.pcec_site_2 = newValues[2] === 'Y' ? 'Y' : 'N';
//             patientStore.details.ABTC.pcec_site_4 = newValues[3] === 'Y' ? 'Y' : 'N';
//         }
//     }
// );
</script>
<template>
    <!-- <div v-if="patientStore.type_prophylaxis === '' || patientStore.type_prophylaxis === null || patientStore.type_prophylaxis === undefined">
        <SelectButton
            v-model="patientStore.type_prophylaxis"
            :options="typesOfProphylaxis"
            aria-labelledby="basic"
            :pt="{
                root: {
                    style: { width: '100%' }
                },
                button: {
                    style: {
                        width: '49%'
                    }
                }
            }"
        />
    </div> -->
    <!-- {{ patientStore.details }} -->

    <div>
        <div class="flex flex-col md:flex-row">
            <div v-if="patientStore.type_prophylaxis !== 'PRE-EXPOSURE'" class="w-full md:w-1/2 p-4" style="height: 60%">
                <div>
                    <div class="flex flex-column">
                        <h6 style="font-weight: bold">BITE / STING</h6>
                        <div class="flex justify-content-between w-1/2 md:w-1/2">
                            <strong style="color: #000080; font-size: 11px">NATURE OF INJURY</strong>
                        </div>
                        <!-- <InputText
                            v-model="patientStore.details.ExternalCauseOfInjury.ext_bite_sp"
                            placeholder="Nature of Injury"
                            :class="{
                                'p-inputtext-filled font-bold mb-2  myCSS-inputtext-required': true,
                                'bg-green-100': patientStore.details.ExternalCauseOfInjury.ext_bite_sp === ''
                            }"
                        /> -->
                        <!-- <div class="flex justify-content-between">
                            <Dropdown
                                v-model="patientStore.details.ExternalCauseOfInjury.animal"
                                style="width: 48%"
                                :options="animalOption"
                                optionLabel="label"
                                optionValue="value"
                                placeholder="Select Animal"
                                :class="{
                                    'p-inputtext-filled font-bold mb-2  myCSS-inputtext-required': true,
                                    'bg-green-100': patientStore.details.ExternalCauseOfInjury.animal === ''
                                }"
                            />
                            <Dropdown
                                v-model="patientStore.details.ExternalCauseOfInjury.cause"
                                style="width: 48%"
                                :options="causeOption"
                                optionLabel="label"
                                optionValue="value"
                                placeholder="Select Cause"
                                :class="{
                                    'p-inputtext-filled font-bold mb-2  myCSS-inputtext-required': true,
                                    'bg-green-100': patientStore.details.ExternalCauseOfInjury.cause === ''
                                }"
                            />
                        </div>
                        <div class="flex justify-content-between">
                            <div style="width: 48%">
                                <Textarea
                                    v-model="patientStore.details.ExternalCauseOfInjury.animal_sp"
                                    v-if="patientStore.details.ExternalCauseOfInjury.animal === 'OTHERS'"
                                    style="width: 100%"
                                    placeholder="Specify Animal"
                                    class="flex justify-content-start"
                                    :class="{
                                        'p-inputtext-filled font-bold mb-2  myCSS-inputtext-required': true,
                                        'bg-green-100': patientStore.details.ExternalCauseOfInjury.animal_sp === ''
                                    }"
                                />
                            </div>
                            <div style="width: 48%">
                                <Textarea
                                    v-if="patientStore.details.ExternalCauseOfInjury.cause === 'OTHERS'"
                                    v-model="patientStore.details.ExternalCauseOfInjury.cause_sp"
                                    style="width: 100%"
                                    class="flex justify-content-end"
                                    placeholder="Specify Cause"
                                    :class="{
                                        'p-inputtext-filled font-bold mb-2  myCSS-inputtext-required': true,
                                        'bg-green-100': patientStore.details.ExternalCauseOfInjury.cause_sp === ''
                                    }"
                                />
                            </div>
                        </div> -->
                        <!-- {{ patientStore.details.ExternalCauseOfInjury.animal }} -->
                        <div v-for="(item, index) in patientStore.details.ExternalCauseOfInjury.animal" :key="index" class="mb-3">
                            <div class="flex justify-content-between">
                                <!-- ANIMAL -->
                                <Dropdown
                                    v-model="patientStore.details.ExternalCauseOfInjury.animal[index]"
                                    style="width: 45%"
                                    :options="animalOption"
                                    optionLabel="label"
                                    optionValue="value"
                                    placeholder="Select Animal"
                                    :class="{
                                        'p-inputtext-filled font-bold mb-2  myCSS-inputtext-required': true,
                                        'bg-green-100': patientStore.details.ExternalCauseOfInjury.animal[index] === ''
                                    }"
                                />

                                <!-- CAUSE + BUTTON -->
                                <Dropdown
                                    v-model="patientStore.details.ExternalCauseOfInjury.cause[index]"
                                    style="width: 45%"
                                    :options="causeOption"
                                    optionLabel="label"
                                    optionValue="value"
                                    placeholder="Select Cause"
                                    :class="{
                                        'p-inputtext-filled font-bold mb-2  myCSS-inputtext-required': true,
                                        'bg-green-100': patientStore.details.ExternalCauseOfInjury.cause[index] === ''
                                    }"
                                />

                                <!-- + BUTTON (only on last item) -->
                                <i style="width: 7%" v-if="index === patientStore.details.ExternalCauseOfInjury.animal.length - 1" class="pi pi-plus" @click="addExternalCause()"></i>
                                <i style="width: 7%" v-else class="pi pi-times" @click="removeExternalCause(index)"></i>
                            </div>

                            <!-- ANIMAL SPECIFY -->

                            <div class="flex justify-content-between">
                                <div style="width: 45%">
                                    <Textarea
                                        v-if="patientStore.details.ExternalCauseOfInjury.animal[index] === 'OTHERS'"
                                        v-model="patientStore.details.ExternalCauseOfInjury.animal_sp[index]"
                                        class="mt-2 flex justify-content-start"
                                        placeholder="Specify Animal"
                                        style="width: 100%"
                                        :class="{
                                            'p-inputtext-filled font-bold mb-2  myCSS-inputtext-required': true,
                                            'bg-green-100': patientStore.details.ExternalCauseOfInjury.animal_sp[index] === ''
                                        }"
                                    />
                                </div>
                                <!-- CAUSE SPECIFY -->
                                <div style="width: 45%">
                                    <Textarea
                                        v-if="patientStore.details.ExternalCauseOfInjury.cause[index] === 'OTHERS'"
                                        v-model="patientStore.details.ExternalCauseOfInjury.cause_sp[index]"
                                        class="mt-2 flex justify-content-end"
                                        placeholder="Specify Cause"
                                        style="width: 100%"
                                        :class="{
                                            'p-inputtext-filled font-bold mb-2  myCSS-inputtext-required': true,
                                            'bg-green-100': patientStore.details.ExternalCauseOfInjury.cause_sp[index] === ''
                                        }"
                                    />
                                </div>
                                <div style="width: 7%"></div>
                            </div>
                        </div>
                    </div>
                    <div class="flex flex-column">
                        <div class="flex justify-content-between w-1/2 md:w-1/2">
                            <strong style="color: #000080; font-size: 11px">BITE CATEGORY</strong>
                        </div>
                        <div style="width: 100%">
                            <Dropdown
                                v-model="patientStore.details.ExternalCauseOfInjury.dogbiteDegree"
                                style="width: 100%"
                                :options="biteDegreeOptions"
                                optionLabel="label"
                                optionValue="value"
                                placeholder="Select Bite Category"
                                :class="{
                                    'p-inputtext-filled font-bold mb-2  myCSS-inputtext-required': true,
                                    'bg-green-100': patientStore.details.ExternalCauseOfInjury.dogbiteDegree === ''
                                }"
                            />
                        </div>
                    </div>
                    <div class="flex flex-column">
                        <div class="flex justify-content-between w-1/2 md:w-1/2">
                            <strong style="color: #000080; font-size: 11px">BLEEDING OF INJURY</strong>
                        </div>
                        <Dropdown
                            v-model="patientStore.details.ExternalCauseOfInjury.bleeding"
                            :options="bleedingOptions"
                            optionLabel="label"
                            optionValue="value"
                            placeholder="Select Bleeding Type"
                            style="width: 100%"
                            :class="{
                                'p-inputtext-filled font-bold mb-2  myCSS-inputtext-required': true,
                                'bg-green-100': patientStore.details.ExternalCauseOfInjury.bleeding === ''
                            }"
                        />
                    </div>
                    <div class="flex flex-column">
                        <div class="flex justify-content-between w-1/2 md:w-1/2">
                            <strong style="color: #000080; font-size: 11px">BITING ANIMAL</strong>
                        </div>
                        <Dropdown
                            v-model="patientStore.details.ExternalCauseOfInjury.bitingAnimal"
                            :options="bitingAnimalOptions"
                            optionLabel="label"
                            optionValue="value"
                            placeholder="Select Animal Status"
                            :class="{
                                'p-inputtext-filled font-bold mb-2  myCSS-inputtext-required': true,
                                'bg-green-100': patientStore.details.ExternalCauseOfInjury.bitingAnimal === ''
                            }"
                        />
                    </div>
                    <div class="flex flex-column">
                        <div class="flex justify-content-between w-1/2 md:w-1/2">
                            <strong style="color: #000080; font-size: 11px">BITING ANIMAL CAN BE OBSERVED</strong>
                        </div>
                        <Dropdown
                            v-model="patientStore.details.ExternalCauseOfInjury.observation"
                            :options="observationOptions"
                            optionLabel="label"
                            optionValue="value"
                            placeholder="Select Observation Status"
                            :class="{
                                'p-inputtext-filled font-bold mb-2  myCSS-inputtext-required': true,
                                'bg-green-100': patientStore.details.ExternalCauseOfInjury.observation === ''
                            }"
                        />
                    </div>

                    <div class="flex flex-column">
                        <div class="flex justify-content-between w-1/2 md:w-1/2">
                            <strong style="color: #000080; font-size: 11px">APPLIED ANYTHING TO WOUND</strong>
                        </div>
                        <Dropdown
                            v-model="patientStore.details.preAdmissionData.first_aid_code"
                            :options="appliedOptions"
                            optionLabel="label"
                            optionValue="value"
                            placeholder="Select Washing Status"
                            :class="{
                                'p-inputtext-filled font-bold mb-2  myCSS-inputtext-required': true,
                                'bg-green-100': patientStore.details.preAdmissionData.first_aid_code === ''
                            }"
                        />
                    </div>

                    <div class="flex flex-column" v-if="patientStore.details.preAdmissionData.first_aid_code === 'Y'">
                        <div class="grid cols-2 justify-content-around m-2">
                            <div style="width: 48%">
                                <div class="flex justify-content-between">
                                    <strong for="generalData.firstaid_others" style="color: #000080" class="text-sm">First Aid</strong>
                                </div>
                                <div class="flex justify-content-end mr-5" v-if="patientStore.details.preAdmissionData.firstaid_others === ''">
                                    <i v-badge.danger="'Value is Required'" style="font-size: 5rem; width: 100%" class="flex justify-content-end" />
                                </div>
                                <InputText
                                    v-model="patientStore.details.preAdmissionData.firstaid_others"
                                    autoResize
                                    placeholder="Enter First Aid"
                                    style="width: 90%"
                                    :class="{
                                        'p-inputtext-filled font-bold mb-2  myCSS-inputtext-required': true,
                                        'bg-green-100': patientStore.details.preAdmissionData.firstaid_others === ''
                                    }"
                                />
                            </div>
                            <div style="width: 48%">
                                <div class="flex justify-content-between">
                                    <strong for="generalData.firstaid_others2" style="color: #000080" class="text-sm">By Whom</strong>
                                </div>
                                <div class="flex justify-content-end mr-5" v-if="patientStore.details.preAdmissionData.firstaid_others2 === ''">
                                    <i v-badge.danger="'Value is Required'" style="font-size: 5rem; width: 100%" class="flex justify-content-end" />
                                </div>
                                <InputText
                                    v-model="patientStore.details.preAdmissionData.firstaid_others2"
                                    autoResize
                                    placeholder="Enter By Whom"
                                    style="width: 90%"
                                    :class="{
                                        'p-inputtext-filled font-bold mb-2  myCSS-inputtext-required': true,
                                        'bg-green-100': patientStore.details.preAdmissionData.firstaid_others2 === ''
                                    }"
                                />
                            </div>
                        </div>
                    </div>
                    <div class="flex flex-column">
                        <div class="flex justify-content-between w-1/2 md:w-1/2">
                            <strong style="color: #000080; font-size: 11px">WASHING OF WOUND DONE</strong>
                        </div>
                        <Dropdown
                            v-model="patientStore.details.ExternalCauseOfInjury.washingDone"
                            :options="washingOptions"
                            optionLabel="label"
                            optionValue="value"
                            placeholder="Select Washing Status"
                            :class="{
                                'p-inputtext-filled font-bold mb-2  myCSS-inputtext-required': true,
                                'bg-green-100': patientStore.details.ExternalCauseOfInjury.washingDone === ''
                            }"
                        />
                    </div>
                    <div style="width: 100%" v-if="patientStore.details.ExternalCauseOfInjury.washingDone === ('YES' || 'Yes') && patientStore.details.preAdmissionData.first_aid_code !== 'Y'">
                        <strong style="color: #000080; font-size: 11px">WASHED BY:</strong>
                        <div style="width: 100%">
                            <Dropdown
                                style="width: 100%"
                                v-model="patientStore.details.preAdmissionData.washingDone_by"
                                :options="[
                                    { label: 'Parent', value: 'PARENT' },
                                    { label: 'Patient', value: 'PATIENT' },
                                    { label: 'Others', value: 'OTHERS' }
                                ]"
                                optionLabel="label"
                                optionValue="value"
                                placeholder="Select Who Washed"
                                :class="{
                                    'p-inputtext-filled font-bold mb-2  myCSS-inputtext-required': true,
                                    'bg-green-100': patientStore.details.ExternalCauseOfInjury.washingDone_by === ''
                                }"
                            />
                        </div>
                        <div style="width: 100%; margin-top: 2px" v-if="patientStore.details.preAdmissionData.washingDone_by === 'OTHERS'">
                            <InputText
                                style="width: 100%"
                                rows="1"
                                v-model="patientStore.details.preAdmissionData.washingDone_by_others"
                                placeholder="Specify Others"
                                :class="{
                                    'p-inputtext-filled font-bold mb-2  myCSS-inputtext-required': true,
                                    'bg-green-100': patientStore.details.ExternalCauseOfInjury.washingDone_by_others === ''
                                }"
                            />
                        </div>
                    </div>
                </div>
            </div>
            <div class="w-full md:w-1/2 p-4" style="height: 60%">
                <h6 style="font-weight: bold">PAST MEDICAL HISTORY</h6>
                <div>
                    <div class="flex flex-column">
                        <div class="flex justify-content-between w-1/2 md:w-1/2">
                            <strong style="color: #000080; font-size: 11px">PREVIOUS COMPLETED ARV</strong>
                        </div>
                        <Dropdown
                            v-model="patientStore.details.ExternalCauseOfInjury.previousARV"
                            :options="observationOptions"
                            optionLabel="label"
                            optionValue="value"
                            placeholder="Previous ARV"
                            :class="{
                                'p-inputtext-filled font-bold mb-2  myCSS-inputtext-required': true,
                                'bg-green-100': patientStore.details.ExternalCauseOfInjury.previousARV === ''
                            }"
                        />
                    </div>
                    <div
                        class="flex flex-column"
                        v-if="patientStore.details.ExternalCauseOfInjury.previousARV === 'YES'"
                        :class="{
                            'p-inputtext-filled font-bold mb-2 myCSS-inputtext-required': true,
                            'bg-green-100': patientStore.details.ExternalCauseOfInjury.arvDate === ''
                        }"
                    >
                        <div class="flex justify-content-between w-1/2 md:w-1/2">
                            <strong style="color: #000080; font-size: 11px">DATE</strong>
                        </div>
                        <div style="width: 100%" class="flex justify-content-center cols-2">
                            <div style="width: 45%" class="flex justify-content-center mr-2">
                                <Calendar style="width: 100%" v-model="yearOnly" view="year" dateFormat="yy" placeholder="Year Only" @date-select="handlePreviousAntiTetanous('year')" />
                            </div>
                            <div style="width: 45%" class="flex justify-content-center ml-2">
                                <Calendar style="width: 100%" v-model="monthYear" view="month" dateFormat="mm/yy" placeholder="Month and Year Only" @date-select="handlePreviousAntiTetanous('month')" />
                            </div>
                        </div>
                        <div style="width: 100%" class="m-1 flex justify-content-center">
                            <Calendar style="width: 92%" v-model="completeDate" dateFormat="mm/dd/yy" placeholder="Complete Date" />
                        </div>
                    </div>
                    <div class="flex flex-column">
                        <div class="flex justify-content-between w-1/2 md:w-1/2">
                            <strong style="color: #000080; font-size: 11px">PREVIOUS ANTI-TETANUS VACCINATION</strong>
                        </div>
                        <Dropdown
                            v-model="patientStore.details.ExternalCauseOfInjury.tetanusVaccination"
                            :options="previousARVOption"
                            optionLabel="label"
                            optionValue="value"
                            placeholder="Previous Anti-Tetanus Vaccination"
                            :class="{
                                'p-inputtext-filled font-bold mb-2  myCSS-inputtext-required': true,
                                'bg-green-100': patientStore.details.ExternalCauseOfInjury.tetanusVaccination === ''
                            }"
                        />
                    </div>
                    <div
                        class="flex justify-content-end"
                        v-if="
                            patientStore.details.ExternalCauseOfInjury.tetanusVaccination === 'Yes' &&
                            (patientStore.details.ExternalCauseOfInjury.tetanusDoses === '' || patientStore.details.ExternalCauseOfInjury.tetanusDoses === undefined) &&
                            (patientStore.details.ExternalCauseOfInjury.lastTetanusDose === '' || patientStore.details.ExternalCauseOfInjury.LastTetanusDose === undefined)
                        "
                    >
                        <small :class="'required-error'" class="text-red-800 text-xs mt-2 font-bold">Value is required</small>
                    </div>
                    <div
                        v-if="patientStore.details.ExternalCauseOfInjury.tetanusVaccination === 'YES'"
                        :class="{
                            'p-inputtext-filled font-bold mb-2  myCSS-inputtext-required': true,
                            'bg-green-100': patientStore.details.ExternalCauseOfInjury.lastTetanusDose === ''
                        }"
                    >
                        <label style="color: #000080; width: 100%; font-size: 11px"># OF DOSES GIVEN</label>
                        <InputNumber v-model="patientStore.details.ExternalCauseOfInjury.tetanusDoses" style="width: 98%" placeholder="Enter number of doses" class="flex justify-content-center ml-1" :max="5" />

                        <label style="color: #000080; font-size: 11px">LAST DOSE GIVEN</label>

                        <div class="flex justify-content-center cols-2" style="width: 100%">
                            <Calendar class="mr-2" style="width: 45%" v-model="lastTetanusDoseYear" view="year" dateFormat="yy" placeholder="Year Only" @date-select="handleLastTetanusDoseSelect('year')" />
                            <Calendar class="ml-2" style="width: 45%" v-model="lastTetanusDoseMonthYear" view="month" dateFormat="mm/yy" placeholder="Month and Year Only" @date-select="handleLastTetanusDoseSelect('month')" />
                        </div>
                        <div class="m-1 flex justify-content-center">
                            <Calendar style="width: 92%" v-model="lastTetanusDoseCompleteDate" dateFormat="mm/dd/yy" placeholder="Complete Date" @date-select="handleLastTetanusDoseSelect('complete')" />
                        </div>
                    </div>

                    <div class="flex flex-column">
                        <div class="flex justify-content-between w-1/2 md:w-1/2">
                            <strong style="color: #000080; font-size: 11px">ALLERGIES</strong>
                        </div>
                        <InputText style="font-weight: bold" v-model="patientStore.details.ExternalCauseOfInjury.allergies" placeholder="Enter Allergies" />
                    </div>

                    <div class="flex flex-column">
                        <div class="flex justify-content-between w-1/2 md:w-1/2">
                            <strong style="color: #000080; font-size: 11px">ADVERSE REACTION FROM PREVIOUS VACCINATION</strong>
                        </div>
                        <InputText style="font-weight: bold" v-model="patientStore.details.ExternalCauseOfInjury.adverseReaction" placeholder="Enter Adverse Reactions" />
                    </div>
                    <div class="flex flex-column">
                        <div class="flex justify-content-between w-1/2 md:w-1/2">
                            <strong style="color: #000080; font-size: 11px">OTHER PERTINENT</strong>
                        </div>
                        <Textarea
                            id="objective"
                            type="text"
                            v-model="patientStore.details.ExternalCauseOfInjury.bite_more_details"
                            autoResize
                            class="font-bold mb-2 mt-1 h-5rem text-xs"
                            style="text-transform: uppercase; width: 100%"
                            placeholder="Details....."
                        />
                        <!-- {{ patientStore.details.ABTC.ats }} -->
                    </div>
                </div>
            </div>
            <div class="w-full md:w-1/2 p-4" v-if="patientStore.progressionDay !== ('' || undefined || null)">
                <VaccineForm />
            </div>
        </div>
        <Fieldset
            style="width: 100%"
            :toggleable="true"
            :collapsed="true"
            :pt="{
                root: { style: { backgroundColor: 'transparent', border: 'none', padding: 'none' } },
                legend: { style: { border: 'none', backgroundColor: 'transparent', textAlign: 'start' } },
                toggler: { style: { padding: '1rem' } }
            }"
        >
            <template #legend>
                <span style="color: #000080" class="font-bold white-space-nowrap">MEDICATION/ANTIBIOTIC</span>
            </template>
            <Textarea
                :pt="{
                    root: {
                        style: {
                            width: '100%',
                            overflow: 'hidden',
                            border: '2px dashed #ccc',
                            borderRadius: '4px',
                            padding: '5px',
                            boxSizing: 'border-box',
                            resize: 'none',
                            backgroundColor: '#ececec',
                            color: '#666',
                            fontWeight: 'bold',
                            fontSize: '13px'
                        }
                    }
                }"
                style="width: 100%"
                v-model="patientStore.details.ABTC.medication"
                class="mt-1 justify-content-center"
                autoResize
            />
        </Fieldset>

        <div
            v-if="patientStore.progressionDay === ('' || undefined || null)"
            :class="
                (patientStore.details.ABTC?.pvrv !== 'Y' &&
                    patientStore.details.ABTC?.pcec !== 'Y' &&
                    patientStore.details.ABTC?.hrig !== 'Y' &&
                    patientStore.details.ABTC?.erig !== 'Y' &&
                    patientStore.details.ABTC?.tt !== 'Y' &&
                    patientStore.details.ABTC?.ats !== 'Y' &&
                    patientStore.details.ABTC?.vaccine_none !== 'Y') ||
                (patientStore.details.ABTC?.pvrv_site_2 !== 'Y' && patientStore.details.ABTC?.pvrv_site_4 !== 'Y' && patientStore.details.ABTC?.pvrv === 'Y') ||
                (patientStore.details.ABTC?.pcec_site_2 !== 'Y' && patientStore.details.ABTC?.pcec_site_4 !== 'Y' && patientStore.details.ABTC?.pcec === 'Y') ||
                (patientStore.details.ABTC?.hrig === 'Y' && patientStore.details.ABTC?.hrig_num === '') ||
                (patientStore.details.ABTC?.erig === 'Y' && patientStore.details.ABTC?.erig_num === '') ||
                (patientStore.details.ABTC?.ats === 'Y' && patientStore.details.ABTC?.ats_num === '')
                    ? 'card custom-shadow mt-3 relative'
                    : 'card mt-3'
            "
            style="width: 100%"
        >
            <h6 class="flex justify-content-center mb-5 font-bold">VACCINE TO BE GIVEN ( {{ patientStore.type_prophylaxis }} )</h6>

            <!-- <div class="grid grid-cols-4 gap-4 flex justify-content-evenly">
                <CheckBoxMultiple class="justify-content-center" style="width: 13%" v-model="patientStore.details.ABTC.pvrv" label="PVRV" />
                <CheckBoxMultiple class="justify-content-center" style="width: 13%" v-model="patientStore.details.ABTC.pcec" label="PCEC" />
                <CheckBoxMultiple v-if="patientStore.type_prophylaxis === 'POST-EXPOSURE'" class="justify-content-center" style="width: 10%" v-model="patientStore.details.ABTC.hrig" label="HRIG" />
                <CheckBoxMultiple v-if="patientStore.type_prophylaxis === 'POST-EXPOSURE'" class="justify-content-center" style="width: 10%" v-model="patientStore.details.ABTC.erig" label="ERIG" />
                <CheckBoxMultiple v-if="patientStore.type_prophylaxis === 'POST-EXPOSURE'" class="justify-content-center" style="width: 10%" v-model="patientStore.details.ABTC.ats" label="ATS" />
                <CheckBoxMultiple class="justify-content-center" style="width: 8%" v-model="patientStore.details.ABTC.tt" label="TT" />
                <CheckBoxMultiple class="justify-content-center" style="width: 8%" v-model="patientStore.details.ABTC.vaccine_none" label="NONE" />
            </div>
            <div class="grid grid-cols-4 gap-4 justify-content-evenly mt-3">
                <div :style="{ width: patientStore.type_prophylaxis === 'PRE-EXPOSURE' ? '25%' : '13%' }">
                    <Transition name="slide-fade" mode="out-in">
                        <div v-if="patientStore.details.ABTC.pvrv === 'Y'" style="width: 100%" class="flex justify-content-evenly mb-2">
                            <CheckBoxMultiple class="flex justify-content-center" style="width: 48%" v-model="patientStore.details.ABTC.pvrv_site_1_id" label="1-site ID" />
                            <CheckBoxMultiple class="flex justify-content-center" style="width: 48%" v-model="patientStore.details.ABTC.pvrv_site_1_im" label="1-site IM" />
                        </div>
                    </Transition>
                </div>
                <div :style="{ width: patientStore.type_prophylaxis === 'PRE-EXPOSURE' ? '25%' : '13%' }">
                    <Transition name="slide-fade" mode="out-in">
                        <div v-if="patientStore.details.ABTC.pcec === 'Y'" style="width: 100%" class="flex justify-content-evenly mb-2">
                            <CheckBoxMultiple class="flex justify-content-center" style="width: 48%" v-model="patientStore.details.ABTC.pcec_site_1_id" label="1-site ID" />
                            <CheckBoxMultiple class="flex justify-content-center" style="width: 48%" v-model="patientStore.details.ABTC.pcec_site_1_im" label="1-site IM" />
                        </div>
                    </Transition>
                </div>
                <div v-if="patientStore.type_prophylaxis === 'POST-EXPOSURE'" style="width: 10%">
                    <Transition name="slide-fade" mode="out-in">
                        <div v-if="patientStore.details.ABTC.hrig === 'Y'" style="width: 100%" class="flex justify-content-evenly">
                            <div class="field">
                                <span class="p-float-label">
                                    <InputNumber type="number" suffix=" mL" :min="0" :max="25" id="hrig" v-model="patientStore.details.ABTC.hrig_num" />          
                                </span>
                            </div>
                        </div>
                    </Transition>
                </div>
                <div v-if="patientStore.type_prophylaxis === 'POST-EXPOSURE'" style="width: 10%">
                    <Transition name="slide-fade" mode="out-in">
                        <div v-if="patientStore.details.ABTC.erig === 'Y'" style="width: 100%" class="flex justify-content-evenly">
                            <div class="field">
                                <span class="p-float-label">
                                    <InputNumber type="number" suffix=" mL" :min="0" :max="25" id="erig" v-model="patientStore.details.ABTC.erig_num" />
                                </span>
                            </div>
                        </div>
                    </Transition>
                </div>
                <div v-if="patientStore.type_prophylaxis === 'POST-EXPOSURE'" style="width: 15%">
                    <Transition name="slide-fade" mode="out-in">
                        <div v-if="patientStore.details.ABTC.ats === 'Y'" style="width: 100%" class="flex justify-content-evenly">
                            <div class="field" style="width: 100%">
                                <span class="p-float-label">
                                    <Dropdown
                                        style="width: 80%"
                                        v-model="patientStore.details.ABTC.ats_num"
                                        :options="[
                                            { label: '1500 ui', value: '1500' },
                                            { label: '3000 ui', value: '3000' },
                                            { label: '4500 ui', value: '4500' },
                                            { label: '6000 ui', value: '6000' }
                                        ]"
                                        optionLabel="label"
                                        optionValue="value"
                                    />
                                    <label for="ats">Amount to be Given</label>
                                </span>
                            </div>
                        </div>
                    </Transition>
                </div>
                <div style="width: 8%"></div>
                <div style="width: 8%"></div>
                <div
                    v-if="
                        (patientStore.details.ABTC.pvrv !== 'Y' &&
                            patientStore.details.ABTC.pcec !== 'Y' &&
                            patientStore.details.ABTC.hrig !== 'Y' &&
                            patientStore.details.ABTC.erig !== 'Y' &&
                            patientStore.details.ABTC.tt !== 'Y' &&
                            patientStore.details.ABTC.ats !== 'Y' &&
                            patientStore.details.ABTC.vaccine_none !== 'Y') ||
                        (patientStore.details.ABTC.pvrv_site_2 !== 'Y' && patientStore.details.ABTC.pvrv_site_4 !== 'Y' && patientStore.details.ABTC.pvrv === 'Y') ||
                        (patientStore.details.ABTC.pcec_site_2 !== 'Y' && patientStore.details.ABTC.pcec_site_4 !== 'Y' && patientStore.details.ABTC.pcec === 'Y') ||
                        (patientStore.details.ABTC.hrig === 'Y' && patientStore.details.ABTC.hrig_num === '') ||
                        (patientStore.details.ABTC.erig === 'Y' && patientStore.details.ABTC.erig_num === '') ||
                        (patientStore.details.ABTC.ats === 'Y' && patientStore.details.ABTC.ats_num === '')
                    "
                    class="bg-red-200 p-2 absolute bottom-0 left-0 text-center text-gray-700 font-semibold italic"
                    style="border-radius: 0 0 1rem 1rem; width: 100%; font-size: 1rem; margin: 0 !important"
                >
                    Value is Required
                </div>
            </div>
            <div class="grid grid-cols-4 gap-4 justify-content-evenly mt-3">
                <div :style="{ width: patientStore.type_prophylaxis === 'PRE-EXPOSURE' ? '25%' : '13%' }">
                    <Transition name="slide-fade" mode="out-in">
                        <div v-if="patientStore.details.ABTC.pvrv === 'Y'" style="width: 100%" class="flex justify-content-evenly mb-2">
                            <CheckBoxMultiple class="flex justify-content-center" style="width: 48%" v-model="patientStore.details.ABTC.pvrv_site_2" label="2-sites" />
                            <CheckBoxMultiple class="flex justify-content-center" style="width: 48%" v-model="patientStore.details.ABTC.pvrv_site_4" label="4-sites" />
                        </div>
                    </Transition>
                </div>
                <div :style="{ width: patientStore.type_prophylaxis === 'PRE-EXPOSURE' ? '25%' : '13%' }">
                    <Transition name="slide-fade" mode="out-in">
                        <div v-if="patientStore.details.ABTC.pcec === 'Y'" style="width: 100%" class="flex justify-content-evenly mb-2">
                            <CheckBoxMultiple class="flex justify-content-center" style="width: 48%" v-model="patientStore.details.ABTC.pcec_site_2" label="2-sites" />
                            <CheckBoxMultiple class="flex justify-content-center" style="width: 48%" v-model="patientStore.details.ABTC.pcec_site_4" label="4-sites" />
                        </div>
                    </Transition>
                </div>
                <div style="width: 10%"></div>
                <div style="width: 10%"></div>
                <div style="width: 10%"></div>
                <div style="width: 8%"></div>
                <div style="width: 8%"></div>
            </div> -->

            <div class="grid grid-cols-4 gap-4 flex justify-content-evenly">
                <CheckBoxMultiple class="justify-content-center" style="width: 13%" v-model="patientStore.details.ABTC.pvrv" label="PVRV" />
                <CheckBoxMultiple class="justify-content-center" style="width: 13%" v-model="patientStore.details.ABTC.pcec" label="PCEC" />
                <CheckBoxMultiple v-if="patientStore.type_prophylaxis === 'POST-EXPOSURE'" class="justify-content-center" style="width: 10%" v-model="patientStore.details.ABTC.hrig" label="HRIG" />
                <CheckBoxMultiple v-if="patientStore.type_prophylaxis === 'POST-EXPOSURE'" class="justify-content-center" style="width: 10%" v-model="patientStore.details.ABTC.erig" label="ERIG" />
                <CheckBoxMultiple v-if="patientStore.type_prophylaxis === 'POST-EXPOSURE'" class="justify-content-center" style="width: 10%" v-model="patientStore.details.ABTC.ats" label="ATS" />
                <CheckBoxMultiple class="justify-content-center" style="width: 8%" v-model="patientStore.details.ABTC.tt" label="TT" />
                <CheckBoxMultiple class="justify-content-center" style="width: 8%" v-model="patientStore.details.ABTC.vaccine_none" label="NONE" />
            </div>
            <div class="grid grid-cols-4 gap-4 justify-content-evenly mt-3">
                <div :style="{ width: patientStore.type_prophylaxis === 'PRE-EXPOSURE' ? '25%' : '13%' }">
                    <Transition name="slide-fade" mode="out-in">
                        <div v-if="patientStore.details.ABTC.pvrv === 'Y'" style="width: 100%" class="flex justify-content-evenly mb-2">
                            <CheckBoxMultiple class="flex justify-content-center" style="width: 48%" v-model="patientStore.details.ABTC.pvrv_site_1_id" label="1-site ID" />
                            <CheckBoxMultiple class="flex justify-content-center" style="width: 48%" v-model="patientStore.details.ABTC.pvrv_site_1_im" label="1-site IM" />
                        </div>
                    </Transition>
                </div>
                <div :style="{ width: patientStore.type_prophylaxis === 'PRE-EXPOSURE' ? '25%' : '13%' }">
                    <Transition name="slide-fade" mode="out-in">
                        <div v-if="patientStore.details.ABTC.pcec === 'Y'" style="width: 100%" class="flex justify-content-evenly mb-2">
                            <CheckBoxMultiple class="flex justify-content-center" style="width: 48%" v-model="patientStore.details.ABTC.pcec_site_1_id" label="1-site ID" />
                            <CheckBoxMultiple class="flex justify-content-center" style="width: 48%" v-model="patientStore.details.ABTC.pcec_site_1_im" label="1-site IM" />
                        </div>
                    </Transition>
                </div>
                <div style="width: 10%">
                    <Transition name="slide-fade" mode="out-in">
                        <div v-if="patientStore.details.ABTC.hrig === 'Y'" style="width: 100%" class="flex justify-content-evenly">
                            <div class="field">
                                <span class="p-float-label">
                                    <InputNumber type="number" suffix=" mL" :min="0" :max="25" id="hrig" v-model="patientStore.details.ABTC.hrig_num" />
                                </span>
                            </div>
                        </div>
                    </Transition>
                </div>
                <div style="width: 10%">
                    <Transition name="slide-fade" mode="out-in">
                        <div v-if="patientStore.details.ABTC.erig === 'Y'" style="width: 100%" class="flex justify-content-evenly">
                            <div style="width: 100%">
                                <label for="Skintest" class="text-black text-xs" style="color: #000080"><i>Skin Test </i></label>
                                <SelectButton
                                    v-model="patientStore.details.ABTC.skintest"
                                    :options="positive_negative_option"
                                    aria-labelledby="basic"
                                    :pt="{
                                        root: {
                                            style: { width: '100%' }
                                        },
                                        button: {
                                            style: {
                                                width: '49%'
                                            }
                                        }
                                    }"
                                />
                            </div>
                        </div>
                    </Transition>
                </div>
                <div style="width: 10%">
                    <Transition name="slide-fade" mode="out-in">
                        <!-- <div v-if="patientStore.details.ABTC.ats === 'Y'" style="width: 100%" class="flex justify-content-evenly">
                            <div class="field" style="width: 100%">
                                <span class="p-float-label">
                                    <Dropdown
                                        style="width: 100%"
                                        v-model="patientStore.details.ABTC.ats_num"
                                        :options="[
                                            { label: '1500 ui', value: '1500' },
                                            { label: '3000 ui', value: '3000' },
                                            { label: '4500 ui', value: '4500' },
                                            { label: '6000 ui', value: '6000' }
                                        ]"
                                        optionLabel="label"
                                        optionValue="value"
                                    />
                                    <label for="ats">Amount to be Given</label>
                                </span>
                            </div>
                        </div> -->
                        <div v-if="patientStore.details.ABTC.ats === 'Y'" style="width: 100%" class="flex justify-content-evenly">
                            <div style="width: 100%">
                                <label for="Skintest" class="text-black text-xs" style="color: #000080"><i>Skin Test </i></label>
                                <SelectButton
                                    v-model="patientStore.details.ABTC.skintest"
                                    :options="positive_negative_option"
                                    aria-labelledby="basic"
                                    :pt="{
                                        root: {
                                            style: { width: '100%' }
                                        },
                                        button: {
                                            style: {
                                                width: '49%'
                                            }
                                        }
                                    }"
                                />
                            </div>
                        </div>
                    </Transition>
                </div>
                <div style="width: 8%"></div>
                <div style="width: 8%"></div>
            </div>
            <div class="grid grid-cols-4 gap-4 justify-content-evenly mt-3">
                <div :style="{ width: patientStore.type_prophylaxis === 'PRE-EXPOSURE' ? '25%' : '13%' }"></div>
                <div :style="{ width: patientStore.type_prophylaxis === 'PRE-EXPOSURE' ? '25%' : '13%' }"></div>
                <div style="width: 10%"></div>
                <div style="width: 10%">
                    <Transition name="slide-fade" mode="out-in">
                        <div v-if="patientStore.details.ABTC.erig === 'Y'" style="width: 100%" class="flex justify-content-evenly">
                            <Transition name="slide-fade" mode="out-in">
                                <div class="field" v-if="patientStore.details.ABTC.skintest === '-' && patientStore.details.ABTC.erig === 'Y'">
                                    <span class="p-float-label">
                                        <InputNumber :minFractionDigits="1" :maxFractionDigits="5" suffix=" mL" :min="0" :max="25" id="erig" v-model="patientStore.details.ABTC.erig_num" />
                                    </span>
                                </div>
                            </Transition>
                        </div>
                    </Transition>
                </div>
                <div style="width: 10%">
                    <Transition name="slide-fade" mode="out-in">
                        <div v-if="patientStore.details.ABTC.ats === 'Y'" style="width: 100%" class="flex justify-content-evenly">
                            <Transition name="slide-fade" mode="out-in">
                                <div class="field" v-if="patientStore.details.ABTC.skintest === '-' && patientStore.details.ABTC.ats === 'Y'">
                                    <!-- <span class="p-float-label">
                                        <InputNumber type="number" suffix=" mL" :min="0" :max="25" id="erig" v-model="patientStore.details.ABTC.ats_num" />
                                    </span> -->
                                    <div v-if="patientStore.details.ABTC.ats === 'Y'" style="width: 100%" class="flex justify-content-evenly">
                                        <div class="field" style="width: 100%">
                                            <span class="p-float-label">
                                                <Dropdown
                                                    style="width: 100%"
                                                    v-model="patientStore.details.ABTC.ats_num"
                                                    :options="[
                                                        { label: '1500 ui', value: '1500' },
                                                        { label: '3000 ui', value: '3000' },
                                                        { label: '4500 ui', value: '4500' },
                                                        { label: '6000 ui', value: '6000' }
                                                    ]"
                                                    optionLabel="label"
                                                    optionValue="value"
                                                />
                                                <label style="width: 100%" for="ats">Amount to be Given</label>
                                            </span>
                                        </div>
                                    </div>
                                </div>
                            </Transition>
                        </div>
                    </Transition>
                </div>
                <div style="width: 8%"></div>
                <div style="width: 8%"></div>
            </div>
            <div class="grid grid-cols-4 gap-4 justify-content-evenly mt-3">
                <div :style="{ width: patientStore.type_prophylaxis === 'PRE-EXPOSURE' ? '25%' : '13%' }">
                    <Transition name="slide-fade" mode="out-in">
                        <div v-if="patientStore.details.ABTC.pvrv === 'Y'" style="width: 100%" class="flex justify-content-evenly mb-2">
                            <CheckBoxMultiple class="flex justify-content-center" style="width: 48%" v-model="patientStore.details.ABTC.pvrv_site_2" label="2-sites" />
                            <CheckBoxMultiple class="flex justify-content-center" style="width: 48%" v-model="patientStore.details.ABTC.pvrv_site_4" label="4-sites" />
                        </div>
                    </Transition>
                </div>
                <div :style="{ width: patientStore.type_prophylaxis === 'PRE-EXPOSURE' ? '25%' : '13%' }">
                    <Transition name="slide-fade" mode="out-in">
                        <div v-if="patientStore.details.ABTC.pcec === 'Y'" style="width: 100%" class="flex justify-content-evenly mb-2">
                            <CheckBoxMultiple class="flex justify-content-center" style="width: 48%" v-model="patientStore.details.ABTC.pcec_site_2" label="2-sites" />
                            <CheckBoxMultiple class="flex justify-content-center" style="width: 48%" v-model="patientStore.details.ABTC.pcec_site_4" label="4-sites" />
                        </div>
                    </Transition>
                </div>
                <div style="width: 10%"></div>
                <div style="width: 10%"></div>
                <div style="width: 10%"></div>
                <div style="width: 8%"></div>
                <div style="width: 8%"></div>
            </div>
        </div>
        <div v-else class="flex justify-content-center">
            <Fieldset
                :class="{ 'bg-green-100': !patientStore.details.ABTC.immunization_schedule }"
                style="width: 98%"
                pt:content:class="flex"
                :pt="{ legend: { style: { border: 'none', backgroundColor: 'transparent' } }, toggler: { style: { padding: '1rem' } } }"
            >
                <template #legend>
                    <span style="color: #000080" class="flex justify-content-center font-bold white-space-nowrap">Vaccine to be Given ( {{ patientStore.type_prophylaxis }} ) </span>
                    <span style="color: blue; font-size: x-small; cursor: pointer; transition: color 0.3s" @click="handleClick" @mouseover="hovering = true" @mouseleave="hovering = false" :style="{ color: hovering ? 'darkblue' : 'blue' }">
                        {{ patientStore?.details?.ABTC?.immunization_schedule }}
                    </span>
                </template>
                <div v-if="patientStore.details.ABTC.immunization_schedule === '' && patientStore.progressionDay !== ('' && null && undefined)">
                    <div style="width: 100%">
                        <label for="Immunization Schedule" class="text-black text-xs" style="color: #000080"><i>Immunization Schedule </i></label>
                        <SelectButton
                            v-model="patientStore.details.ABTC.immunization_schedule"
                            :options="immunizationOption"
                            aria-labelledby="basic"
                            :pt="{
                                root: {
                                    style: { width: '100%' }
                                },
                                button: {
                                    style: {
                                        width: '49%'
                                    }
                                }
                            }"
                        />
                    </div>
                </div>
                <div v-else>
                    <div style="width: 100%" v-if="patientStore.details.ABTC.booster_regimen === '' && patientStore.details.ABTC.immunization_schedule === 'BOOSTER'">
                        <div style="width: 100%">
                            <label for="Booster Regimen" class="text-black text-xs" style="color: #000080"><i>Booster Regimen </i></label>
                            <SelectButton
                                v-model="patientStore.details.ABTC.booster_regimen"
                                :options="boosterRegimenOption"
                                aria-labelledby="basic"
                                :pt="{
                                    root: {
                                        style: { width: '100%' }
                                    },
                                    button: {
                                        style: {
                                            width: '49%'
                                        }
                                    }
                                }"
                            />
                        </div>
                    </div>
                    <div v-else>
                        <div class="grid grid-cols-4 gap-4 flex justify-content-evenly">
                            <div
                                class="justify-content-center"
                                style="width: 26%"
                                :style="{ width: patientStore.type_prophylaxis === 'PRE-EXPOSURE' ? '22%' : '26%', height: ['Y'].includes(patientStore.details.ABTC.pvrv) || ['Y'].includes(patientStore.details.ABTC.pcec) ? '20vh' : '8vh' }"
                            >
                                <div>
                                    <CheckBoxMultiple class="flex justify-content-center" v-model="patientStore.details.ABTC.pvrv" label="PVRV" />
                                    <div v-if="patientStore.details.ABTC.pvrv === 'Y'" style="width: 100%" class="flex justify-content-evenly mt-5">
                                        <CheckBoxMultiple class="flex justify-content-center" style="width: 48%" v-model="patientStore.details.ABTC.pvrv_site_1_id" label="1-site ID" />
                                        <CheckBoxMultiple class="flex justify-content-center" style="width: 48%" v-model="patientStore.details.ABTC.pvrv_site_1_im" label="1-site IM" />
                                    </div>
                                    <div v-if="patientStore.details.ABTC.pvrv === 'Y'" style="width: 100%" class="flex justify-content-evenly mt-4">
                                        <CheckBoxMultiple class="flex justify-content-center" style="width: 48%" v-model="patientStore.details.ABTC.pvrv_site_2" label="2-sites ID" />
                                        <CheckBoxMultiple class="flex justify-content-center" style="width: 48%" v-model="patientStore.details.ABTC.pvrv_site_4" label="4-sites ID" />
                                    </div>
                                </div>
                                <div class="mt-2">
                                    <CheckBoxMultiple class="justify-content-center" v-model="patientStore.details.ABTC.pcec" label="PCEC" />
                                    <div v-if="patientStore.details.ABTC.pcec === 'Y'" style="width: 100%" class="flex justify-content-evenly mt-5">
                                        <CheckBoxMultiple class="flex justify-content-center" style="width: 48%" v-model="patientStore.details.ABTC.pcec_site_1_id" label="1-site ID" />
                                        <CheckBoxMultiple class="flex justify-content-center" style="width: 48%" v-model="patientStore.details.ABTC.pcec_site_1_im" label="1-site IM" />
                                    </div>
                                    <div v-if="patientStore.details.ABTC.pcec === 'Y'" style="width: 100%" class="flex justify-content-evenly mt-4">
                                        <CheckBoxMultiple class="flex justify-content-center" style="width: 48%" v-model="patientStore.details.ABTC.pcec_site_2" label="2-sites ID" />
                                        <CheckBoxMultiple class="flex justify-content-center" style="width: 48%" v-model="patientStore.details.ABTC.pcec_site_4" label="4-sites ID" />
                                    </div>
                                </div>
                                <!-- </div>sass="justify-content-center" :style="{ width: patientStore.type_prophylaxis === 'PRE-EXPOSURE' ? '22%' : '13%', height: patientStore.details.ABTC.pcec === 'Y' ? '20vh' : '5vh' }"> -->
                            </div>
                            <div style="width: 20%" :style="{ width: patientStore.type_prophylaxis === 'PRE-EXPOSURE' ? '0%' : '20%', height: patientStore.details.ABTC.hrig === 'Y' || patientStore.details.ABTC.erig === 'Y' ? '20vh' : '8vh' }">
                                <div>
                                    <CheckBoxMultiple v-if="patientStore.type_prophylaxis === 'POST-EXPOSURE'" class="justify-content-center" v-model="patientStore.details.ABTC.hrig" label="HRIG" />
                                    <InputNumber style="width: 100%" v-if="patientStore.details.ABTC.hrig === 'Y'" class="mt-4" type="number" suffix=" mL" :min="0" :max="25" id="hrig" v-model="patientStore.details.ABTC.hrig_num" />
                                </div>
                                <!-- </div>
                            <div style="width: 10%" :style="{ width: patientStore.type_prophylaxis === 'PRE-EXPOSURE' ? '0%' : '10%', height: patientStore.details.ABTC.erig === 'Y' ? '22vh' : '5vh' }"> -->
                                <div class="mt-2">
                                    <CheckBoxMultiple v-if="patientStore.type_prophylaxis === 'POST-EXPOSURE'" class="justify-content-center" v-model="patientStore.details.ABTC.erig" label="ERIG" />
                                    <div v-if="patientStore.details.ABTC.erig === 'Y'" style="width: 100%" class="flex justify-content-evenly">
                                        <div style="width: 100%">
                                            <label for="Skintest" class="text-black text-xs" style="color: #000080"><i>Skin Test </i></label>
                                            <SelectButton
                                                v-model="patientStore.details.ABTC.skintest"
                                                :options="positive_negative_option"
                                                aria-labelledby="basic"
                                                :pt="{
                                                    root: {
                                                        style: { width: '100%' }
                                                    },
                                                    button: {
                                                        style: {
                                                            width: '49%'
                                                        }
                                                    }
                                                }"
                                            />
                                        </div>
                                    </div>
                                    <Transition name="slide-fade" mode="out-in">
                                        <div class="field mt-2" v-if="patientStore.details.ABTC.skintest === '-' && patientStore.details.ABTC.erig === 'Y'">
                                            <span class="p-float-label">
                                                <InputNumber style="width: 100%" :minFractionDigits="1" :maxFractionDigits="5" suffix=" mL" :min="0" :max="25" id="erig" v-model="patientStore.details.ABTC.erig_num" />
                                            </span>
                                        </div>
                                    </Transition>
                                </div>
                            </div>

                            <!-- <div style="width: 10%" :style="{ width: patientStore.type_prophylaxis === 'PRE-EXPOSURE' ? '0%' : '10%', height: patientStore.details.ABTC.ats === 'Y' ? '22    vh' : '5vh' }"></div> -->
                            <div :style="{ width: patientStore.type_prophylaxis === 'PRE-EXPOSURE' ? '0%' : '15%', height: patientStore.details.ABTC.ats === 'Y' ? '15vh' : '8vh' }">
                                <CheckBoxMultiple v-if="patientStore.type_prophylaxis === 'POST-EXPOSURE'" class="justify-content-center" v-model="patientStore.details.ABTC.ats" label="ATS" />
                                <div v-if="patientStore.details.ABTC.ats === 'Y'" style="width: 100%" class="flex justify-content-evenly">
                                    <div style="width: 100%">
                                        <label for="Skintest" class="text-black text-xs" style="color: #000080"><i>Skin Test </i></label>
                                        <SelectButton
                                            v-model="patientStore.details.ABTC.skintest"
                                            :options="positive_negative_option"
                                            aria-labelledby="basic"
                                            :pt="{
                                                root: {
                                                    style: { width: '100%' }
                                                },
                                                button: {
                                                    style: {
                                                        width: '49%'
                                                    }
                                                }
                                            }"
                                        />
                                    </div>
                                </div>
                                <Transition name="slide-fade" mode="out-in" style="width: 100%">
                                    <div class="field mt-2" v-if="patientStore.details.ABTC.skintest === '-' && patientStore.details.ABTC.ats === 'Y'">
                                        <div v-if="patientStore.details.ABTC.ats === 'Y'" style="width: 100%" class="flex justify-content-evenly">
                                            <div class="field" style="width: 100%">
                                                <span class="p-float-label">
                                                    <Dropdown
                                                        style="width: 100%"
                                                        v-model="patientStore.details.ABTC.ats_num"
                                                        :options="[
                                                            { label: '1500 ui', value: '1500' },
                                                            { label: '3000 ui', value: '3000' },
                                                            { label: '4500 ui', value: '4500' },
                                                            { label: '6000 ui', value: '6000' }
                                                        ]"
                                                        optionLabel="label"
                                                        optionValue="value"
                                                    />
                                                    <label style="width: 100%" for="ats">Amount to be Given</label>
                                                </span>
                                            </div>
                                        </div>
                                    </div>
                                </Transition>
                            </div>
                            <div :style="{ width: patientStore.type_prophylaxis === 'PRE-EXPOSURE' ? '22%' : '10%' }" style="height: 5vh">
                                <CheckBoxMultiple v-model="patientStore.details.ABTC.tt" label="TT" style="width: 100%" class="flex justify-content-center" />
                            </div>
                            <div :style="{ width: patientStore.type_prophylaxis === 'PRE-EXPOSURE' ? '22%' : '23%', height: patientStore.details.ABTC.vaccine_none === 'Y' ? '20vh' : '5vh' }">
                                <CheckBoxMultiple v-model="patientStore.details.ABTC.opted" label="OPTED" style="width: 100%" class="flex justify-content-center" />
                                <CheckBoxMultiple v-model="patientStore.details.ABTC.vaccine_none" label="NONE" style="width: 100%" class="flex justify-content-center" />
                                <SelectButton
                                    v-if="patientStore.details.ABTC.vaccine_none === 'Y'"
                                    class="mt-3"
                                    v-model="patientStore.details.ABTC.vaccine_none_sp"
                                    :options="vaccineNoneOption"
                                    aria-labelledby="basic"
                                    :pt="{
                                        root: {
                                            style: { width: '100%' }
                                        },
                                        button: {
                                            style: {
                                                width: '49%'
                                            }
                                        }
                                    }"
                                />
                                <div v-if="patientStore.details.ABTC.vaccine_none_sp === 'STILL COVERED' && patientStore.details.ABTC.vaccine_none === 'Y'">
                                    <label style="color: #000080; width: 100%; font-size: 11px">Follow-Up Date</label>
                                    <Calendar @date-select="handleCoverdDateSelect()" style="width: 92%" v-model="coveredDate" dateFormat="mm/dd/yy" placeholder="Complete Date" />
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </Fieldset>
        </div>
    </div>
</template>
<style>
.rainbow-border {
    border: 1px solid transparent;
    border-image: linear-gradient(to right, hsl(30, 56%, 89%), #e8e8af, #96d996, #7171df, #bf8ee2, #c99cdc) 1;
    border-radius: 1px;
    padding: 1px;
    background-color: #f9f9f9;
}

.slide-fade-enter-active {
    transition: all 0.4s ease-out;
}

.slide-fade-leave-active {
    transition: all 0.8s cubic-bezier(1, 0.5, 0.8, 1);
}

.slide-fade-enter-from,
.slide-fade-leave-to {
    transform: translateY(20px);
    opacity: 0;
}

.bg::before {
    content: '';
    background: url('@/assets/images/BGHMC.png') no-repeat center center fixed;
    opacity: 0.1;
}

.slide-fade-enter-active {
    transition: all 0.3s ease-out;
}

.slide-fade-leave-active {
    transition: all 0.3s cubic-bezier(1, 0.5, 0.8, 1);
}

.slide-fade-enter-from,
.slide-fade-leave-to {
    transform: translateX(20px);
    opacity: 0;
}

.custom-shadow {
    box-shadow: 0 2px 7px rgba(255, 0, 0, 0.5);
    transition: box-shadow 0.3s ease;
}

.custom-shadow:hover {
    box-shadow: 0 6px 20px rgba(255, 0, 0, 0.75);
}
</style>
